"""add sms_opt_in to applications

Revision ID: 2cbdb5dd7a3e
Revises: fdd051410d8c
Create Date: 2026-02-16 05:35:22.604579
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbdb5dd7a3e'
down_revision: Union[str, None] = 'fdd051410d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('sms_opt_in', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'sms_opt_in')
    # ### end Alembic commands ###
