"""add acceptance_sent_at to users

Revision ID: b7d1a2c3e4f5
Revises: 2cbdb5dd7a3e
Create Date: 2026-03-18 22:55:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7d1a2c3e4f5'
down_revision: str | None = '2cbdb5dd7a3e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('acceptance_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'acceptance_sent_at')
    # ### end Alembic commands ###
