"""add contact info legal agreements and marketing fields to applications

Revision ID: fdd051410d8c
Revises: c5af14dc13fa
Create Date: 2026-02-16 05:26:05.173357
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd051410d8c'
down_revision: Union[str, None] = 'c5af14dc13fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('email', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('age_confirmed', sa.Boolean(), nullable=False))
    op.add_column('applications', sa.Column('code_of_conduct_accepted', sa.Boolean(), nullable=False))
    op.add_column('applications', sa.Column('liability_waiver_accepted', sa.Boolean(), nullable=False))
    op.add_column('applications', sa.Column('how_did_you_hear', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('resume_sharing_opt_in', sa.Boolean(), nullable=False))
    op.add_column('applications', sa.Column('email_opt_in', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'email_opt_in')
    op.drop_column('applications', 'resume_sharing_opt_in')
    op.drop_column('applications', 'how_did_you_hear')
    op.drop_column('applications', 'liability_waiver_accepted')
    op.drop_column('applications', 'code_of_conduct_accepted')
    op.drop_column('applications', 'age_confirmed')
    op.drop_column('applications', 'email')
    op.drop_column('applications', 'phone_number')
    # ### end Alembic commands ###
